---
version: "3.6"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}-amd64
    restart: always
    container_name: elasticsearch
    volumes:
      - ${PWD}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${PWD}/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ${PWD}/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${PWD}/elasticsearch/config/certs:/usr/share/elasticsearch/config/certs
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    restart: always
    volumes:
      - ${PWD}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on: ["elasticsearch"]
    healthcheck:
      test: curl -s http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  # enterprise-search:
  #   image: ccr.ccs.tencentyun.com/elastic-mirror/other:enterprise-search
  #   container_name: enterprise-search
  #   restart: always
  #   volumes:
  #     - ${PWD}/enterprise-search/enterprise-search.yml:/usr/share/enterprise-search/config/enterprise-search.yml
  #   depends_on: ["elasticsearch"]
  #   healthcheck:
  #     test: curl -s http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  es-metricbeat:
    image: docker.elastic.co/beats/metricbeat-oss:${TAG}
    container_name: es-metricbeat
    restart: always
    volumes:
      - ${PWD}/es-metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ${PWD}/es-metricbeat/modules.d:/usr/share/metricbeat/modules.d

  apm-server:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: apm-server
    restart: always
    volumes:
      - ${PWD}/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
