---
version: "3.6"
services:
  elasticsearch:
    networks:
      - default

  kibana:
    networks:
      - default

  # enterprise-search:
  #   networks:
  #     - default

  es-metricbeat:
    networks:
      - default

  apm-server:
    networks:
      - default
networks:
  default:
    external:
      name: external_default
